# -*- coding: utf-8 -*-
"""Clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10urHNWqZ56FseWm4iFtICcasIPQcto-V

## 導入必要套件
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.colors import ListedColormap
from collections import defaultdict, deque
from typing import List, Tuple, Dict, Optional
import math
import random
import heapq
import json

# 設定中文字體
plt.rcParams['font.sans-serif'] = ['Microsoft YaHei', 'SimHei']
plt.rcParams['axes.unicode_minus'] = False

print("套件載入完成")

"""## 資料輸入：倉庫地圖與MapMask載入"""

import pandas as pd
import numpy as np

class WarehouseLoader:
    @staticmethod
    def load_layout_and_mask(layout_csv='倉庫.csv', mapmask_csv='MapMask_preview.csv'):
        print(f"正在載入倉庫配置({layout_csv}) 與 MapMask({mapmask_csv})...")
        layout = pd.read_csv(layout_csv, header=None)
        mapmask = pd.read_csv(mapmask_csv, header=None).values

        if layout.shape != mapmask.shape:
            raise ValueError(f"Layout 與 MapMask 形狀不符：{layout.shape} vs {mapmask.shape}")

        print(f"載入成功：倉庫 {layout.shape}，可行走格 {np.sum(mapmask==1)}，障礙格 {np.sum(mapmask==0)}")
        return layout, mapmask

"""## 建立倉庫（Warehouse對象）、倉庫可視化、避障機制(mapmask套用)"""

import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict, deque

class Warehouse:
    def __init__(self, layout: np.ndarray, mapmask: np.ndarray):
        self.layout = layout
        self.mapmask = mapmask
        self.rows, self.cols = layout.shape

        # 建立儲位查詢（item name <-> 座標）
        self.storage_map = {}
        self.item_to_locations = defaultdict(list)
        for y in range(self.rows):
            for x in range(self.cols):
                val = layout[y, x]
                if val != 0:  # 非通道就是貨品
                    item = str(int(val))
                    self.storage_map[(x, y)] = item
                    self.item_to_locations[item].append((x, y))

    def is_walkable(self, x, y):
        return (0 <= x < self.cols) and (0 <= y < self.rows) and self.mapmask[y, x] == 1

    def get_neighbors(self, x, y):
        for dx, dy in [(1,0), (-1,0), (0,1), (0,-1)]:
            nx, ny = x+dx, y+dy
            if self.is_walkable(nx, ny):
                yield (nx, ny)

    def visualize(self, figsize=(10,6), depot=None):
        plt.figure(figsize=figsize)
        plt.imshow(self.mapmask, cmap='gray_r')
        # 標註貨品
        for (x, y), item in self.storage_map.items():
            plt.text(x, y, item, ha='center', va='center', fontsize=7,
                     color='red', fontweight='bold')
        if depot:
            plt.scatter([depot[0]], [depot[1]], c='green', s=120, marker='*', label='Depot')
        plt.title("倉庫地圖 (紅字=貨品，綠=主站)")
        plt.legend()
        plt.grid(True, alpha=0.2)
        plt.show()

    # 基礎BFS找路徑（回傳最短路徑list），for debug/可視化，不處理碰撞/避讓
    def bfs_path(self, start, goal):
        queue = deque([(start, [start])])
        visited = set([start])
        while queue:
            (x, y), path = queue.popleft()
            if (x, y) == goal:
                return path
            for nx, ny in self.get_neighbors(x, y):
                if (nx, ny) not in visited:
                    visited.add((nx, ny))
                    queue.append(((nx, ny), path + [(nx, ny)]))
        return None  # 無法到達

"""## 訂單生成器Starter Code"""

import random

class OrderGenerator:
    def __init__(self, A_items, B_items, C_items, class_weights=(0.1, 0.2, 0.7)):
        self.item_pool = {'A': A_items, 'B': B_items, 'C': C_items}
        self.class_labels = ['A', 'B', 'C']
        self.class_weights = class_weights

    def generate_single_order(self, min_items=10, max_items=50):
        k = random.randint(min_items, max_items)
        # 按指定比例抽取
        item_classes = random.choices(self.class_labels, weights=self.class_weights, k=k)
        order = [random.choice(self.item_pool[cls]) for cls in item_classes]
        return order

    def generate_orders(self, n_orders=1000, min_items=3, max_items=38):
        orders = []
        for _ in range(n_orders):
            orders.append(self.generate_single_order(min_items, max_items))
        return orders

# ===== 實例化並測試
A_items = [f"A{i}" for i in range(1, 11)]         # A1~A10
B_items = [f"B{i}" for i in range(11, 51)]        # B11~B50
C_items = [f"C{i}" for i in range(51, 101)]       # C51~C100

order_gen = OrderGenerator(A_items, B_items, C_items, class_weights=(0.1, 0.2, 0.7))

# 產生單筆訂單
order = order_gen.generate_single_order()
print("單筆訂單：", order)

# 批次產生1000筆（回傳 list of list）
all_orders = order_gen.generate_orders(n_orders=1000)
# 可以統計驗證分布
flat = [x for order in all_orders for x in order]
print(f"A佔{sum(i.startswith('A') for i in flat)/len(flat):.2%}，B佔{sum(i.startswith('B') for i in flat)/len(flat):.2%}，C佔{sum(i.startswith('C') for i in flat)/len(flat):.2%}")

"""## Dijkstra 與地圖距離查詢層"""

import heapq
import numpy as np
from collections import deque

class Warehouse:
    # ...（保留上一層的 __init__、is_walkable、visualize等）
    def __init__(self, layout: np.ndarray, mapmask: np.ndarray):
        self.layout = layout
        self.mapmask = mapmask
        self.rows, self.cols = layout.shape

        # 建立儲位查詢（item name <-> 座標）
        self.storage_map = {}
        self.item_to_locations = defaultdict(list)
        for y in range(self.rows):
            for x in range(self.cols):
                val = layout[y, x]
                if val != 0:  # 非通道就是貨品
                    item = str(int(val))
                    self.storage_map[(x, y)] = item
                    self.item_to_locations[item].append((x, y))

    def is_walkable(self, x, y):
        return (0 <= x < self.cols) and (0 <= y < self.rows) and self.mapmask[y, x] == 1

    def get_neighbors(self, x, y):
        for dx, dy in [(1,0), (-1,0), (0,1), (0,-1)]:
            nx, ny = x+dx, y+dy
            if self.is_walkable(nx, ny):
                yield (nx, ny)

    def visualize(self, figsize=(10,6), depot=None):
        plt.figure(figsize=figsize)
        plt.imshow(self.mapmask, cmap='gray_r')
        # 標註貨品
        for (x, y), item in self.storage_map.items():
            plt.text(x, y, item, ha='center', va='center', fontsize=7,
                     color='red', fontweight='bold')
        if depot:
            plt.scatter([depot[0]], [depot[1]], c='green', s=120, marker='*', label='Depot')
        plt.title("倉庫地圖 (紅字=貨品，綠=主站)")
        plt.legend()
        plt.grid(True, alpha=0.2)
        plt.show()

    # -- BFS: 單一最短步數路徑 --
    def bfs_path(self, start, goal):
        queue = deque([(start, [start])])
        visited = set([start])
        while queue:
            (x, y), path = queue.popleft()
            if (x, y) == goal:
                return path
            for nx, ny in self.get_neighbors(x, y):
                if (nx, ny) not in visited:
                    visited.add((nx, ny))
                    queue.append(((nx, ny), path + [(nx, ny)]))
        return None

    # -- Dijkstra: 支援加權最短距離 --
    def dijkstra_distance(self, start, goal, weight_func=None):
        # weight_func(a, b): 回傳 a到b 的耗能/距離，預設每步1
        if start == goal:
            return 0.0
        visited = set()
        heap = [(0, start)]
        dist_map = {start: 0}
        while heap:
            cost, node = heapq.heappop(heap)
            if node == goal:
                return cost
            if node in visited:
                continue
            visited.add(node)
            for neighbor in self.get_neighbors(*node):
                weight = weight_func(node, neighbor) if weight_func else 1.0
                new_cost = cost + weight
                if neighbor not in dist_map or new_cost < dist_map[neighbor]:
                    dist_map[neighbor] = new_cost
                    heapq.heappush(heap, (new_cost, neighbor))
        return float('inf')

    # -- 距離矩陣 --
    def calculate_distance_matrix(self, points, use_dijkstra=True, weight_func=None):
        n = len(points)
        mat = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                if i == j:
                    mat[i, j] = 0
                elif use_dijkstra:
                    mat[i, j] = self.dijkstra_distance(points[i], points[j], weight_func)
                else:
                    path = self.bfs_path(points[i], points[j])
                    mat[i, j] = len(path) - 1 if path else float('inf')
        return mat

"""## 目標式及獎懲"""

import math
from typing import Dict, List, Tuple, Optional
import numpy as np

class WarehouseEvaluatorLite:
    """
    評分器（輕量版）
    - 目標：Z = γ * E_total + δ * Ct，預設 Ct 用距離（公尺），E_total為粗略能耗
    - 懲罰：未覆蓋、重複、單趟容量、負載平衡、必須 depot 出發與返回
    需求資料（local / 本訂單）：
      data["distance_small"] : (S,S) 距離矩陣（local索引0..S-1；0是depot）
      data["coord_small"]    : 長度S的座標[(row,col), ...]，用於轉彎統計（可省略）
      data["depot_small"]    : 0
      data["tasks_small"]    : [1..M]
      data["max_items_per_trip"] : int，每趟最多件數（全車一樣）
      # 可選：
      data["trip_capacity_per_agv"] : {agv_id: cap, ...} 覆蓋單車容量
      data["task_requirements"]     : {task_idx: required_times, ...} 若同一貨格要拿多次
      data["cell_m"] : 每一 BFS 步長（格長）對應的公尺，預設 1.0
    能耗參數（必要）：
      v, m_vehicle, m_item, mu, g, M_turn, theta_per_turn, lift_h, lift_eta, P_idle, T_idle_per_pick
    """
    def __init__(self, gamma: float = 0.0, delta: float = 1.0,
                 penalty_weights: Optional[Dict[str, float]] = None,
                 load_balance_delta: int = 3):
        assert abs((gamma + delta) - 1.0) < 1e-9, "需要 γ+δ=1"
        self.gamma = gamma
        self.delta = delta
        self.lb_delta = load_balance_delta
        # 懲罰權重（可用 penalty_weights 覆蓋）
        self.W = {
            "coverage":       1e6,  # 任務未覆蓋
            "each_task_once": 1e6,  # 任務被多做
            "trip_capacity":  5e5,  # 單趟容量超限（統一只用這一種）
            "load_balance":   1e4,  # 軟性負載平衡
            "depot_trip":     1e6,  # 沒有從 depot 出發或返回
        }
        if penalty_weights:
            self.W.update(penalty_weights)

    # 目標式 Z = γE + δCt（E、Ct 若沒外部提供，我們用距離估）
    def objective(self, E_total: float, Ct: float) -> float:
        return self.gamma * float(E_total) + self.delta * float(Ct)

    # ✅ 以走道距離 + 參數計算四類能耗 & Ct
    def compute_E_and_Ct(self, solution: Dict, data: Dict):
        D     = data["distance_small"]          # S×S（subset距離，單位=格數）
        coord = data.get("coord_small")         # subset索引 -> (row,col)
        cell_m = float(data.get("cell_m", 1.0)) # 每格幾公尺，預設 1

        # 參數
        v   = float(data["v"])
        m0  = float(data["m_vehicle"])
        m1  = float(data["m_item"])
        mu  = float(data["mu"])
        g   = float(data["g"])
        M_t = float(data["M_turn"])
        dth = float(data["theta_per_turn"])
        h   = float(data["lift_h"])
        eta = float(data["lift_eta"])
        Pid = float(data["P_idle"])
        Tid = float(data["T_idle_per_pick"])

        total_dist_m = 0.0
        E_trans = 0.0   # 平移: 加速 + 滾動
        E_rot   = 0.0   # 轉向
        E_lift  = 0.0   # 升降
        E_idle  = 0.0   # 待機

        for trips in solution.values():
            for trip in trips:
                path = trip["path"]            # local索引，例如 [0,12,27,0]
                edges = list(zip(path, path[1:]))

                # 距離（轉公尺）
                seg_dist_cells = sum(float(D[a, b]) for a, b in edges)
                seg_dist_m = seg_dist_cells * cell_m
                total_dist_m += seg_dist_m

                # 本趟件數 & 載重
                items = path[1:-1]             # 去掉首尾 depot
                n_items = len(items)
                m_total = m0 + m1 * n_items

                # —— E_trans: 滾動 + 加速（簡化：每條邊視為一次加速事件）
                N_accel = len(edges)
                E_roll  = mu * m_total * g * seg_dist_m            # J
                E_accel = 0.5 * m_total * (v ** 2) * N_accel       # J
                E_trans += E_roll + E_accel

                # —— E_rot: 轉彎次數 × 每次角度能耗
                if coord is not None and len(edges) >= 2:
                    turns = 0
                    for (a, b), (b2, c) in zip(edges, edges[1:]):
                        ax, ay = coord[a]; bx, by = coord[b]; cx, cy = coord[c]
                        v1 = (bx - ax, by - ay)
                        v2 = (cx - bx, cy - by)
                        if v1 != (0, 0) and v2 != (0, 0):
                            # 只要方向變化（含180度掉頭）就算一次轉彎
                            cross = v1[0]*v2[1] - v1[1]*v2[0]
                            dot   = v1[0]*v2[0] + v1[1]*v2[1]
                            if cross != 0 or dot < 0:
                                turns += 1
                    E_rot += M_t * dth * turns

                # —— E_lift: 每件一次升降（若你們是整盤一次，改成 *1）
                if n_items > 0:
                    E_lift += (m1 * g * h / max(eta, 1e-9)) * n_items

                # —— E_idle: 每件停等固定時間
                E_idle += Pid * (Tid * n_items)

        E_total = E_trans + E_rot + E_lift + E_idle
        Ct = total_dist_m
        return E_total, Ct

    # 懲罰（限制式）
    def penalty(self, solution: Dict, data: Dict) -> float:
        p = 0.0
        depot = data["depot_small"]
        tasks = set(data["tasks_small"])
        max_items_global = int(data.get("max_items_per_trip", 5))
        caps_per_agv = data.get("trip_capacity_per_agv", None)  # 可為 None 或 {agv_id: cap}
        # 若有「需求次數」，用它來判斷少拿/多拿；沒有就等同每任務=1次
        requirements: Optional[Dict[int, int]] = data.get("task_requirements", None)

        # (0) 每趟必須 depot 出發又回 depot
        for k, trips in solution.items():
            for trip in trips:
                path = trip["path"]
                if not (len(path) >= 2 and path[0] == depot and path[-1] == depot):
                    p += self.W["depot_trip"]

        # 統計：每任務被做幾次；檢查單趟容量
        count_per_task = {m: 0 for m in tasks}
        for k, trips in solution.items():
            for trip in trips:
                items = [n for n in trip["path"][1:-1] if n in tasks]
                # 容量限制（若指定每車容量，用它；否則用全域最大值）
                limit = max_items_global if caps_per_agv is None else caps_per_agv.get(k, max_items_global)
                if len(items) > limit:
                    p += self.W["trip_capacity"] * (len(items) - limit)
                for m in items:
                    count_per_task[m] += 1

        # 覆蓋 / 唯一 or 需求次數
        if requirements is None:
            not_covered = [m for m,c in count_per_task.items() if c == 0]
            duplicates  = sum(max(0, c-1) for c in count_per_task.values())
        else:
            not_covered = []
            duplicates = 0
            for m_need, need in requirements.items():
                got = count_per_task.get(m_need, 0)
                if got < need:
                    not_covered.append(m_need)          # 少拿
                if got > need:
                    duplicates += (got - need)          # 多拿
        p += self.W["coverage"] * len(not_covered)
        p += self.W["each_task_once"] * duplicates

        # (2) 軟性負載平衡（以「件數」衡量）
        tasks_per_agv = []
        for k, trips in solution.items():
            cnt = sum(len([n for n in trip["path"][1:-1] if n in tasks]) for trip in trips)
            tasks_per_agv.append(cnt)
        if tasks_per_agv:
            avg = sum(tasks_per_agv) / len(tasks_per_agv)
            over = sum(max(0, abs(c - avg) - self.lb_delta) for c in tasks_per_agv)
            p += self.W["load_balance"] * over

        return p

    # 總分
    def score(self, solution: Dict, data: Dict, E_total: float = None, Ct: float = None) -> float:
        if E_total is None or Ct is None:
            E_total, Ct = self.compute_E_and_Ct(solution, data)
        return self.objective(E_total, Ct) + self.penalty(solution, data)

"""## ACO分配層(Starter Code)"""

import numpy as np
import random

class SimpleACO:
    def __init__(self, points, distance_matrix, start_idx=0, n_ants=10, n_iter=80, alpha=1, beta=4, evaporation=0.5, q=100):
        self.points = points
        self.distances = distance_matrix  # 距離矩陣 (NxN)
        self.n = len(points)
        self.n_ants = n_ants
        self.n_iter = n_iter
        self.alpha = alpha  # 費洛蒙重要性
        self.beta = beta    # 距離重要性
        self.evaporation = evaporation
        self.q = q
        self.start_idx = start_idx

        self.pheromones = np.ones((self.n, self.n))
        self.best_path = None
        self.best_distance = float('inf')

    def solve(self):
        for iteration in range(self.n_iter):
            all_paths = []
            all_distances = []
            for ant in range(self.n_ants):
                path, distance = self._construct_solution()
                all_paths.append(path)
                all_distances.append(distance)
                if distance < self.best_distance:
                    self.best_distance = distance
                    self.best_path = path.copy()
            self._update_pheromones(all_paths, all_distances)
        return self.best_path, self.best_distance

    def _construct_solution(self):
        current = self.start_idx
        unvisited = set(range(self.n))
        unvisited.remove(current)
        path = [current]
        total_distance = 0
        while unvisited:
            next_city = self._select_next_city(current, unvisited)
            path.append(next_city)
            total_distance += self.distances[current][next_city]
            current = next_city
            unvisited.remove(next_city)
        path.append(self.start_idx)  # 回到起點
        total_distance += self.distances[current][self.start_idx]
        return path, total_distance

    def _select_next_city(self, current, unvisited):
        probabilities = []
        for city in unvisited:
            pheromone = self.pheromones[current][city] ** self.alpha
            distance = max(self.distances[current][city], 0.001)
            visibility = (1.0 / distance) ** self.beta
            probabilities.append(pheromone * visibility)
        total = sum(probabilities)
        if total == 0:
            return random.choice(list(unvisited))
        probabilities = [p / total for p in probabilities]
        r = random.random()
        cumulative = 0
        cities = list(unvisited)
        for i, prob in enumerate(probabilities):
            cumulative += prob
            if r <= cumulative:
                return cities[i]
        return cities[-1]

    def _update_pheromones(self, all_paths, all_distances):
        self.pheromones *= (1 - self.evaporation)
        for path, distance in zip(all_paths, all_distances):
            if distance == 0:
                continue
            pheromone_deposit = self.q / distance
            for i in range(len(path) - 1):
                from_city = path[i]
                to_city = path[i + 1]
                self.pheromones[from_city][to_city] += pheromone_deposit
                self.pheromones[to_city][from_city] += pheromone_deposit

"""## 多AGV分批分配總控函式"""

def aco_batch_allocation(warehouse, order_items, depot, num_agv=3, max_batch=5):
    """
    輸入:
        warehouse: Warehouse物件
        order_items: list of str (貨品名稱)
        depot: (x,y)起點座標
    輸出:
        dict, key為 AGV-1, AGV-2, ...，值為每台AGV每批次的最優路徑（含順序）
    """
    # 1. 取得所有貨品座標
    item_locations = []
    for item in order_items:
        candidates = warehouse.item_to_locations[item]
        # 假設一件貨多個儲位，先取距depot最近的
        loc = min(candidates, key=lambda p: warehouse.dijkstra_distance(depot, p))
        item_locations.append(loc)

    # 2. 分批：每台AGV一批，超過max_batch自動多批（順序可再優化）
    batches = [item_locations[i:i+max_batch] for i in range(0, len(item_locations), max_batch)]
    agv_paths = {}
    for i, batch in enumerate(batches):
        # 建距離矩陣（起點+批次貨品）
        points = [depot] + batch
        dist_mat = warehouse.calculate_distance_matrix(points, use_dijkstra=True)
        aco = SimpleACO(points, dist_mat, start_idx=0)
        best_path, best_distance = aco.solve()
        # 轉換成貨品位置順序
        ordered_points = [points[idx] for idx in best_path]
        agv_name = f'AGV-{(i%num_agv)+1}'  # 多批自動分給多台AGV輪流
        agv_paths.setdefault(agv_name, []).append(ordered_points)
    return agv_paths

"""## Display"""

def main():
    # 1. 載入地圖
    layout, mapmask = WarehouseLoader.load_layout_and_mask("倉庫.csv", "MapMask_preview.csv")
    warehouse = Warehouse(layout.values, mapmask)  # pandas df to numpy

    # 2. 設定主站與產生訂單
    depot = (15,0)
    order_items = order_gen.generate_single_order(min_items=10, max_items=50)  # 自訂數量範圍

    # 3. 多AGV分批與ACO分配
    agv_paths = aco_batch_allocation(warehouse, order_items, depot, num_agv=3, max_batch=5)
    # agv_paths: {AGV-1: [[(depot, ...座標..., depot)], ...], ...}

    # 4. solution/data 整合
    solution, coord_small = build_solution_for_evaluator(agv_paths, warehouse, depot, order_items)
    distance_small = warehouse.calculate_distance_matrix(coord_small, use_dijkstra=True)
    data = {
        "distance_small": distance_small,
        "coord_small": coord_small,
        "depot_small": 0,
        "tasks_small": list(range(1, len(coord_small))),
        "max_items_per_trip": 5,
        # 能耗參數
        "cell_m": 1.0,
        "v": 1.0, "m_vehicle": 100, "m_item": 10, "mu": 0.02, "g": 9.8,
        "M_turn": 1.0, "theta_per_turn": math.pi/2,
        "lift_h": 1.0, "lift_eta": 0.8, "P_idle": 5, "T_idle_per_pick": 2,
    }

    # 5. 評分
    evaluator = WarehouseEvaluatorLite(gamma=0.3, delta=0.7)
    E_total, Ct = evaluator.compute_E_and_Ct(solution, data)
    penalty = evaluator.penalty(solution, data)
    score = evaluator.score(solution, data, E_total, Ct)
    print("能耗：", E_total, "距離目標：", Ct, "罰分：", penalty, "總分：", score)

    # 6. 每台AGV結果
    for agv, trips in solution.items():
        print(f"{agv}:")
        for i, trip in enumerate(trips):
            print(f"  批次{i+1}: local index {trip['path']}，貨格: {[coord_small[idx] for idx in trip['path'][1:-1]]}")

    # 7. 每步座標csv
    records = []
    for agv, batch_routes in agv_paths.items():
        for batch_idx, route in enumerate(batch_routes, start=1):
            for step_idx, (x, y) in enumerate(route):
                action = "move"
                if step_idx == 0:
                    remarks = "start at depot"
                elif step_idx == len(route) - 1:
                    action = "return"
                    remarks = "back to depot"
                else:
                    remarks = ""
                records.append({
                    "agv_id": agv,
                    "batch": batch_idx,
                    "step": step_idx + 1,
                    "x": x, "y": y,
                    "action": action,
                    "remarks": remarks
                })
    move_df = pd.DataFrame(records)
    move_df.to_csv("agv_move_detail.csv", index=False)
    print("已輸出每步移動路徑到 agv_move_detail.csv")

# 工具：build solution for evaluator
def build_solution_for_evaluator(agv_paths, warehouse, depot, order_items):
    coord_small = [depot]
    for item in order_items:
        loc = min(warehouse.item_to_locations[item], key=lambda p: warehouse.dijkstra_distance(depot, p))
        if loc not in coord_small:
            coord_small.append(loc)
    solution = {}
    for agv, batch_routes in agv_paths.items():
        trips = []
        for route in batch_routes:
            local_path = [0]
            for pos in route[1:-1]:
                local_path.append(coord_small.index(pos))
            local_path.append(0)
            trips.append({"path": local_path})
        solution[agv] = trips
    return solution, coord_small

if __name__ == "__main__":
    main()
